kind: pipeline
type: docker
name: default

trigger:
  branch: 
    - main
  event: 
    - push
    - pull_request

steps:
  - name: tests
    image: denoland/deno:alpine-1.22.3
    commands:
      - deno test --allow-read
